### ISSUE TITLE
Prep for release

### ISSUE THREAD

**Issue by dogancanbakir** [projectdiscovery/urlfinder#2]
```[tasklist]
### Tasks
- [ ] https://github.com/projectdiscovery/urlfinder/issues/3
- [ ] https://github.com/projectdiscovery/urlfinder/issues/4
- [ ] https://github.com/projectdiscovery/urlfinder/issues/5
- [ ] https://github.com/projectdiscovery/urlfinder/issues/6
```
